# Command: fluffcore hats HatName UserName
Hats:
  Cake:
    CustomModel: 14
    Name: "&d&lGrand Reopening Hat"
    TranslatableKey: "fluffCore.cakeHat"
    TranslatableKeyDesc: "fluffCore.cakeHatDesc"
    TranslatableKeyDesc1: "fluffCore.cakeHatDesc1"
    Lore:
      - "&r"
      - "&fGotten from the 2021"
      - "&fReopening Quest!"
      - "&r"
  Cat:
    CustomModel: 15
    Name: "&e&lCuddly Kitty Cat Hat"
    TranslatableKey: "fluffCore.catHat"
    TranslatableKeyDesc: "fluffCore.catHatDesc"
    TranslatableKeyDesc1: ""
    Lore:
      - "&r"
      - "&fA nice cuddly kitty cat"
      - "&fto sit in your hand or head!"
      - "&r"
  Strawberry:
    CustomModel: 16
    Name: "&e&lStrawberry Hat"
    TranslatableKey: "fluffCore.strawberryHat"
    TranslatableKeyDesc: "fluffCore.strawberryHatDesc"
    TranslatableKeyDesc1: ""
    Lore:
      - "&r"
      - "&fEver feel like your life doesn't have"
      - "&fenough strawberries? Try wearing one!"
      - "&r"
  Egg:
    CustomModel: 17
    Name: "&e&lEgg Hat"
    TranslatableKey: "fluffCore.eggHat"
    TranslatableKeyDesc: "fluffCore.eggHatDesc"
    TranslatableKeyDesc1: ""
    Lore:
      - "&r"
      - "&fWhat better than Scrambled?"
      - "&fOvereasy & Sunny Side Up!"
      - "&r"
      
      
